<?php
session_start();
require __DIR__ . '/config.php';

function h($v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function url(string $path=''): string { return CB_BASE . '/' . ltrim($path, '/'); }
function csrf(): string { if (empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(24)); return $_SESSION['csrf']; }
function check_csrf(): void { if (!hash_equals($_SESSION['csrf'] ?? '', $_POST['csrf'] ?? '')) { http_response_code(419); exit('Page expired. Refresh and try again.'); } }
function user(): ?array { return $_SESSION['user'] ?? null; }
function require_login(): void { if (!user()) { header('Location: '.url('login')); exit; } }
function is_admin(): bool { return (bool)(user()['admin'] ?? false); }
function q(string $sql, array $p=[]): array { $s=db()->prepare($sql); $s->execute($p); return $s->fetchAll(); }
function one(string $sql, array $p=[]): ?array { $r=q($sql,$p); return $r[0] ?? null; }
function execq(string $sql,array $p=[]): int { $s=db()->prepare($sql); $s->execute($p); return $s->rowCount(); }

if (($_GET['page'] ?? '') === 'logout') { session_destroy(); header('Location: '.url('login')); exit; }
if ($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action'] ?? '')==='login') {
    check_csrf(); $email=trim($_POST['email']??''); $pass=$_POST['password']??''; $found=one("SELECT id,first_name,last_name,name,email,password,organisation_id,1 administrator FROM users WHERE email=? AND deleted_at IS NULL AND active=1 LIMIT 1",[$email]);
    if (!$found) $found=one("SELECT id,first_name,last_name,name,email,password,1 organisation_id,1 administrator FROM admins WHERE email=? AND deleted_at IS NULL AND active=1 LIMIT 1",[$email]);
    if ($found && password_verify($pass,$found['password'])) { $_SESSION['user']=['id'=>(int)$found['id'],'name'=>$found['name'] ?: trim($found['first_name'].' '.$found['last_name']),'email'=>$found['email'],'org'=>(int)$found['organisation_id'],'admin'=>(bool)$found['administrator']]; header('Location: '.url('')); exit; }
    $error='Invalid email or password.';
}
require_login();
$page=$_GET['page']??'';
if ($_SERVER['REQUEST_METHOD']==='POST' && $page==='save') {
    check_csrf(); if (!is_admin()) { http_response_code(403); exit('Forbidden'); }
    $type=$_POST['type']??''; $id=(int)($_POST['id']??0); $org=user()['org'];
    if ($type==='client') { $data=[trim($_POST['name']??''),trim($_POST['phone']??''),trim($_POST['website']??''),trim($_POST['city']??''),$org,user()['id']]; if($id) execq('UPDATE clients SET name=?,phone=?,website=?,city=? WHERE id=? AND organisation_id=?',[$data[0],$data[1],$data[2],$data[3],$id,$org]); else execq('INSERT INTO clients(name,phone,website,city,organisation_id,user_id,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,NOW(),NOW())',$data); }
    if ($type==='project') { $client=(int)$_POST['client_id']; if($id) execq('UPDATE projects SET name=?,client_id=?,description=?,start_at=?,end_at=?,status_id=? WHERE id=? AND organisation_id=?',[trim($_POST['name']),$client,trim($_POST['description']),$_POST['start_at']?:date('Y-m-d'),$_POST['end_at']?:null,(int)($_POST['status_id']??1),$id,$org]); else execq('INSERT INTO projects(name,client_id,description,start_at,end_at,status_id,user_id,organisation_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NOW(),NOW())',[trim($_POST['name']),$client,trim($_POST['description']),$_POST['start_at']?:date('Y-m-d'),$_POST['end_at']?:null,(int)($_POST['status_id']??1),user()['id'],$org]); }
    header('Location: '.url($type.'s')); exit;
}
if ($page==='delete' && is_admin() && isset($_GET['type'],$_GET['id'])) { $map=['client'=>'clients','project'=>'projects','task'=>'tasks','ticket'=>'tickets']; $t=$map[$_GET['type']]??null; if($t) execq("UPDATE $t SET deleted_at=NOW() WHERE id=? AND organisation_id=?",[(int)$_GET['id'],user()['org']]); header('Location: '.url($_GET['type'].'s')); exit; }

$org=user()['org'];
$counts=['clients'=>0,'projects'=>0,'tasks'=>0,'tickets'=>0];
foreach($counts as $k=>$_) { $row=one("SELECT COUNT(*) n FROM $k WHERE organisation_id=? AND deleted_at IS NULL",[$org]); $counts[$k]=(int)($row['n']??0); }
function layout_start(string $title): void { global $page; echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.h($title).' · '.h(CB_APP_NAME).'</title><link rel="stylesheet" href="'.h(url('style.css')).'"></head><body><aside><div class="brand">C’est Bon<span>Portal</span></div><nav><a class="'.($page===''?'on':''). '" href="'.url(''). '">Dashboard</a><a class="'.($page==='clients'?'on':'').'" href="'.url('clients').'">Clients</a><a class="'.($page==='projects'?'on':'').'" href="'.url('projects').'">Projects</a><a class="'.($page==='tasks'?'on':'').'" href="'.url('tasks').'">Tasks</a><a class="'.($page==='tickets'?'on':'').'" href="'.url('tickets').'">Tickets</a><a class="'.($page==='calendar'?'on':'').'" href="'.url('calendar').'">Calendar</a></nav><div class="user">'.h(user()['name']).'<small>'.h(user()['email']).'</small><a href="'.url('logout').'">Sign out</a></div></aside><main><header><div><div class="eyebrow">Client & Business Portal</div><h1>'.h($title).'</h1></div>'.(is_admin()?'<span class="badge">Admin</span>':'').'</header>'; }
function layout_end(): void { echo '</main></body></html>'; }
function table_page(string $type,string $title,string $sql,array $headers): void { global $org; layout_start($title); $rows=q($sql,[$org]); echo '<section class="panel"><div class="toolbar"><strong>'.count($rows).' records</strong>'.(is_admin()&&in_array($type,['client','project'])?'<a class="btn" href="'.url($type.'-new').'">+ Add</a>':'').'</div><div class="table-wrap"><table><thead><tr>'; foreach($headers as $h) echo '<th>'.h($h).'</th>'; echo '</tr></thead><tbody>'; foreach($rows as $r){ echo '<tr>'; foreach(array_keys($headers) as $k) echo '<td>'.h($r[$k]??'').'</td>'; echo '</tr>'; } if(!$rows) echo '<tr><td colspan="'.count($headers).'" class="empty">Nothing here yet.</td></tr>'; echo '</tbody></table></div></section>'; layout_end(); }

if ($page==='clients') { table_page('client','Clients',"SELECT id,name,phone,website,city,IF(active=1,'Active','Inactive') status FROM clients WHERE organisation_id=? AND deleted_at IS NULL ORDER BY name",['name'=>'Name','phone'=>'Phone','website'=>'Website','city'=>'City','status'=>'Status']); exit; }
if ($page==='projects') { table_page('project','Projects',"SELECT p.id,p.name,c.name client,p.start_at,p.end_at,p.status_id FROM projects p LEFT JOIN clients c ON c.id=p.client_id WHERE p.organisation_id=? AND p.deleted_at IS NULL ORDER BY p.id DESC",['name'=>'Project','client'=>'Client','start_at'=>'Start','end_at'=>'End','status_id'=>'Status']); exit; }
if ($page==='tasks') { table_page('task','Tasks',"SELECT id,title,priority_id,status_id,deadline_at FROM tasks WHERE organisation_id=? AND deleted_at IS NULL ORDER BY deadline_at IS NULL,deadline_at",['title'=>'Task','priority_id'=>'Priority','status_id'=>'Status','deadline_at'=>'Deadline']); exit; }
if ($page==='tickets') { table_page('ticket','Tickets',"SELECT id,subject,priority_id,status_id,last_reply_at FROM tickets WHERE organisation_id=? AND deleted_at IS NULL ORDER BY last_reply_at DESC",['subject'=>'Subject','priority_id'=>'Priority','status_id'=>'Status','last_reply_at'=>'Last reply']); exit; }
if ($page==='calendar') { layout_start('Calendar'); $events=q('SELECT name,start_date,end_date,description FROM events WHERE organisation_id=? AND deleted_at IS NULL ORDER BY start_date',[$org]); echo '<section class="panel"><div class="calendar">'; foreach($events as $e) echo '<article><time>'.h(date('M j, Y g:i A',strtotime($e['start_date']))).'</time><h3>'.h($e['name']).'</h3><p>'.h($e['description']).'</p></article>'; if(!$events) echo '<div class="empty">No events scheduled.</div>'; echo '</div></section>'; layout_end(); exit; }
if ($page==='client-new'||$page==='project-new') { if(!is_admin()){http_response_code(403);exit('Forbidden');} $type=$page==='client-new'?'client':'project'; layout_start($type==='client'?'New Client':'New Project'); echo '<section class="panel form">'; if($type==='client') echo '<form method="post" action="'.url('save').'">'.csrf_field().' <input type="hidden" name="type" value="client"><label>Name*<input required name="name"></label><label>Phone<input name="phone"></label><label>Website<input name="website"></label><label>City<input name="city"></label><button class="btn">Save client</button></form>'; else { $clients=q('SELECT id,name FROM clients WHERE organisation_id=? AND deleted_at IS NULL ORDER BY name',[$org]); echo '<form method="post" action="'.url('save').'">'.csrf_field().'<input type="hidden" name="type" value="project"><label>Name*<input required name="name"></label><label>Client<select required name="client_id">'; foreach($clients as $c) echo '<option value="'.(int)$c['id'].'">'.h($c['name']).'</option>'; echo '</select></label><label>Description<textarea name="description"></textarea></label><label>Start<input type="date" name="start_at" value="'.date('Y-m-d').'"></label><label>End<input type="date" name="end_at"></label><button class="btn">Save project</button></form>'; } echo '</section>'; layout_end(); exit; }
function csrf_field(): string { return '<input type="hidden" name="csrf" value="'.h(csrf()).'">'; }
layout_start('Dashboard'); echo '<section class="hero"><div><h2>Welcome back, '.h(user()['name']).'.</h2><p>Your C’est Bon workspace is ready.</p></div></section><section class="stats">'; foreach($counts as $k=>$v) echo '<a class="stat" href="'.url($k).'" ><span>'.h(ucfirst($k)).'</span><strong>'.(int)$v.'</strong><small>View all →</small></a>'; echo '</section><section class="grid2"><div class="panel"><h3>Quick actions</h3><div class="actions"><a class="btn" href="'.url('clients').'">Clients</a><a class="btn secondary" href="'.url('projects').'">Projects</a><a class="btn secondary" href="'.url('tickets').'">Support tickets</a></div></div><div class="panel"><h3>System</h3><p class="muted">Standalone PHP edition · MySQL · Hostinger ready.</p></div></section>'; layout_end();
